### ISSUE TITLE
License Inspection Screen / Profile Icon

### ISSUE THREAD

**Issue by ekt003** [pyrophone/beneath#32]
If you exit to the map at any time from the hunter's license inspection screen, you go back to the inspection screen, not the profile page when you click the profile icon. Maybe get rid of the 'X' altogether and only have a 'Return to Profile' option?

https://docs.google.com/spreadsheets/d/1Jt57In3kTezAQVb4niir3sTJuS9qcZEhKicnykK_40c/edit#gid=162677487

Row 18

**Comment by pyrophone** [comment]
Patched through my lastest push, will be built later
